### ISSUE TITLE
Don't hardcode /dev/sda0 as boot device

### ISSUE THREAD

**Issue by Geertiebear** [managarm/managarm#322]
This requires several changes.

- Make udev expose /dev/disk/by-uuid/
- Make libblockfs support more than one partition and table
- Get root partition from kernel command line

Is realistically needed to boot off real hardware, since disk discovery order is non-deterministic.

**Comment by avdgrinten** [comment]
This will also require starting udevd in init stage1. Doing that should not run into any road blocks since udevd already works from init stage2. We can gracefully shut down udevd before entering stage 2 such that stage 2 re-runs udev rules after the rootfs is available (which should be a no-op anyway since these rules should be idempotent).

**Comment by qookei** [comment]
This was solved by #707, although by having libblockfs tag partitions that have a specific type UUID and having init-stage1 look for that partition, instead of using udev in init-stage1.
