### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by tizbac** [managarm/managarm#57]
Hi, where do i find dependencies like helix and cofiber? i have found only stuff that seems unrelated, sorry if it is a stupid question but really i can't find anything useful

**Comment by avdgrinten** [comment]
Sorry for not replying earlier. This issue was posted during a period when I was busy with other things and I forgot about it.

In general, the dependencies are either in this repository (like helix) or in other repositories of the @managarm organization (like frigg) or my own Github account (like libcofiber). However, to build the project, it is not necessary to download them yourself. Check out the managarm/bootstrap-managarm repository for build instructions.
